### ISSUE TITLE
Questions about the doom's action space

### ISSUE THREAD

**Issue by NoListen** [hardmaru/WorldModelsExperiments#7]
We know that the doom's action space is discrete(3).

Have you tried using discrete actions instead of transferring them to continuous action？ 

Will one single continuous action be more beneficial/efficient in the evolution strategy ?

**Comment by hardmaru** [comment]
Hi @NoListen 

I haven't tried on the 3 discrete action space, bit it should work (although the ES algorithm might converge slower since you will have 3 times the number of parameters to optimize for).

So having one continuous action is more beneficial in the sense that optimizing for it with an ES is more efficient.

**Comment by NoListen** [comment]
Thanks for your reply.
